name: Deploy to GitHub Pages

# ###the repo should have a .gitattributes with the content "* binary" to prevent git from modifying files.

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    # use ubuntu-latest image to run steps in
    runs-on: ubuntu-latest

    steps:
      # uses GitHub's checkout action to checkout code from the master branch
      - uses: actions/checkout@v3

      # sets the .Bet SKD to version 6.0.x
      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: "6.0.x"
          # dotnet-quality: "preview"
      # publish Blazor project to the build folder
      - name: "Publish with .NET"
        run: dotnet publish --nologo --configuration release --output build

      # changes the base-tag in index.html from '/' to "  " to match GitHub Pages repository subdirectory. Replace wasm-github-pages for repo name
      - name: Change base-tag in index.html from / to
        run: sed -i 's/<base href="\/" \/>/<base href="\/pages\/" \/>/g' build/wwwroot/index.html

      # copy index.html to 404.html to server the same file when a file is not found. This allows Blazor to handle not found requests.
      - name: Copy index.html to 404.html
        run: cp build/wwwroot/index.html build/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders to start with underscore)
      - name: Add .nojekyll file
        run: touch build/wwwroot/.nojekyll

      # fix file permisions
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          name: github-pages
          path: build

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2.0.3
